#!/bin/bash
sed -i '/^HWADDR/d' /etc/sysconfig/network-scripts/ifcfg-eth* && sed -i '/^UUID/d' /etc/sysconfig/network-scripts/ifcfg-eth*
rm -rf /etc/udev/rules.d/70-persistent*
rm -f /var/lib/dhclient/*
rm -f /etc/ssh/*key*
