#!/bin/bash

IP=$1
NETMASK=$2
GATEWAY=$3

sed -i -e "s/\(^IPADDR=\).*/\1${1}/" -e "s/\(^GATEWAY=\).*/\1${3}/" -e "s/\(^NETMASK=\).*/\1${2}/" /etc/sysconfig/network-scripts/ifcfg-eth0
sed -i -e "s/\(^GRAFANA_BASE.*http\:\/\/\).*\(\:3000\)/\1${1}\2/" /var/www/orkweb/.env


echo "IP Address change to ${1}"

echo "Restart network service. Please connect to new ip address"

service network restart

#echo ${1}/${2} $3
#/etc/sysconfig/network-scripts/ifcfg-eth0 
