---

- hosts: "{{ variable_host | default('all') }}"
  become: true
  gather_facts: no

  vars:
    doc_root: /var/www/orkweb
    configs_path: /home/IRW/all_include/Configs
    yamls_path: /home/IRW/all_include/Yamls
    scripts_path: /home/IRW/all_include/Scripts
    user: admin
    password: admin

  vars_prompt:


   - name: "station_name"
     prompt: "Please Enter Station Name ?"
     private: no

   - name: "ip"
     prompt: "Please Enter station Ip address?"
     private: no
     confirm: yes

   - name: "center_ip"
     prompt: "Please Enter Center Ip address ?"
     private: no
     confirm: yes

  tasks:

    - include: "{{ yamls_path }}/railway_agent.yml"
      





